export const newMovie1 = {
  id: 3,
  name: 'new movie 1',
  koreanName: '살인자',
  summary: '새로운 영화 1 줄거리',
  imageUrl: 'images/movieinput1.png',
  averageRate: '4.0',
  grade: 19,
  reservationRate: '19.0',
  runningTime: 110,
  openingDate: '2023.5.1',
  closingDate: '2023.5.16',
  movieStatusesId: 1,
  hallTypes: ['Suite Cinema', 'Standard'],
};

export const newMovie2 = {
  id: 4,
  name: 'new movie 2',
  koreanName: '미션파서블3',
  summary: '새로운 영화 2 줄거리',
  imageUrl: 'images/movieinput2.png',
  averageRate: '2.0',
  grade: 15,
  reservationRate: '15.0',
  runningTime: 100,
  openingDate: '2023.6.1',
  closingDate: '2023.6.16',
  movieStatusesId: 1,
  hallTypes: ['Cine de Chef'],
};

export const newMovie3 = {
  id: 5,
  name: 'new movie 3',
  koreanName: '그가 사라졌다 ',
  summary: '새로운 영화 3 줄거리',
  imageUrl: 'images/movieinput3.png',
  averageRate: '3.8',
  grade: 12,
  reservationRate: '12.0',
  runningTime: 95,
  openingDate: '2023.7.1',
  closingDate: '2023.7.16',
  movieStatusesId: 1,
  hallTypes: ['Standard'],
};
export const newMovie4 = {
  id: 6,
  name: 'new movie 3',
  koreanName: '아낙수나문',
  summary: '새로운 영화 3 줄거리',
  imageUrl: 'images/movieinput4.png',
  averageRate: '3.8',
  grade: 12,
  reservationRate: '10.0',
  runningTime: 95,
  openingDate: '2023.7.1',
  closingDate: '2023.7.16',
  movieStatusesId: 1,
  hallTypes: ['Standard'],
};
